management:
  endpoints:
    web:
      exposure:
        include: "*"

sentry:
  environment: development
  traces-sample-rate: 0.5
  send-default-pii: true
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: info
  attach-threads: true
  attach-stacktrace: true