management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
    jmx:
      exposure:
        exclude: "*"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false